import type {
  KnowledgeCapsule,
} from "./types";

export const knowledgeCapsules: KnowledgeCapsule[] = [
  {
    id: "capsule-143",
    identity: "KP-2026-000143",
    title: "Governance Foundations",
    summary:
      "Constitutional and architectural knowledge package for authority, provenance, approval and activation boundaries.",
    stage: "Validation",
    destination: "Canonical Review",
    state: "needs-review",
    integrity: "peeling",
    authority: "Architectural",
    confidence: 87,
    owner: "Knowledge Governance",
    approval: "Human review required",
    packageType: "Educational",
    mission: "Chief Agent Readiness",
    compiler: "Documentation Compiler",
    educationalModule: "Governance Foundations",
    consumer: "Chief Agent Education",
    failedLayer: "Provenance",
    remediation:
      "Confirm conversation lineage and attach the governing architectural decision.",
    responsibleAuthority: "Architecture",
    blockedDependencies: [
      "ADR lineage confirmation",
      "Conversation authority review",
    ],
    layers: [
      {
        id: "authority",
        label: "Authority",
        status: "healthy",
        detail: "Architectural authority confirmed.",
      },
      {
        id: "provenance",
        label: "Provenance",
        status: "failed",
        detail: "Two source references lack complete lineage.",
      },
      {
        id: "confidence",
        label: "Confidence",
        status: "warning",
        detail: "Confidence reduced pending provenance remediation.",
      },
      {
        id: "education",
        label: "Educational Mapping",
        status: "healthy",
        detail: "Mapped to Governance Foundations.",
      },
    ],
  },
  {
    id: "capsule-144",
    identity: "KP-2026-000144",
    title: "Repository Operations",
    summary:
      "Repository engineering knowledge package covering build, validation and controlled implementation practices.",
    stage: "Knowledge Package Assembly",
    destination: "Canonical Review",
    state: "validated",
    integrity: "sealed",
    authority: "Operational",
    confidence: 96,
    owner: "Repository Engineering",
    approval: "Validated",
    packageType: "Engineering",
    mission: "Platform Delivery",
    compiler: "Git Compiler",
    educationalModule: "Repository Operations",
    consumer: "Engineering Standards",
    layers: [
      {
        id: "authority",
        label: "Authority",
        status: "healthy",
        detail: "Operational authority confirmed.",
      },
      {
        id: "provenance",
        label: "Provenance",
        status: "healthy",
        detail: "Repository history and build lineage complete.",
      },
      {
        id: "confidence",
        label: "Confidence",
        status: "healthy",
        detail: "High-confidence implementation evidence.",
      },
      {
        id: "education",
        label: "Educational Mapping",
        status: "healthy",
        detail: "Mapped to Repository Operations.",
      },
    ],
  },
  {
    id: "capsule-145",
    identity: "KP-2026-000145",
    title: "Mission Continuity",
    summary:
      "Mission knowledge package preserving objectives, operating boundaries and continuity rules.",
    stage: "Organizational Memory",
    destination: "Chief Agent Education",
    state: "published",
    integrity: "sealed",
    authority: "Constitutional",
    confidence: 99,
    owner: "Executive Governance",
    approval: "Approved",
    packageType: "Mission",
    mission: "Mission Continuity",
    compiler: "Mission Compiler",
    educationalModule: "Genesis Corpus",
    consumer: "Mission Planning",
    layers: [
      {
        id: "authority",
        label: "Authority",
        status: "healthy",
        detail: "Constitutional authority confirmed.",
      },
      {
        id: "provenance",
        label: "Provenance",
        status: "healthy",
        detail: "Mission corpus lineage complete.",
      },
      {
        id: "confidence",
        label: "Confidence",
        status: "healthy",
        detail: "Validated mission evidence.",
      },
      {
        id: "education",
        label: "Educational Mapping",
        status: "healthy",
        detail: "Mapped to Genesis Corpus.",
      },
    ],
  },
  {
    id: "capsule-146",
    identity: "KP-2026-000146",
    title: "Conversation Decision Lineage",
    summary:
      "Conversation-derived package preserving architectural corrections, decisions and educational contribution.",
    stage: "Conversation Compiler",
    destination: "Knowledge IR",
    state: "processing",
    integrity: "sealed",
    authority: "Architectural",
    confidence: 91,
    owner: "Chief Agent Program",
    approval: "Pending validation",
    packageType: "Conversation",
    mission: "Knowledge Preservation",
    compiler: "Conversation Compiler",
    educationalModule: "Decision Intelligence",
    consumer: "Educational Corpus",
    layers: [
      {
        id: "authority",
        label: "Authority",
        status: "healthy",
        detail: "Conversation authority classified.",
      },
      {
        id: "provenance",
        label: "Provenance",
        status: "healthy",
        detail: "Conversation thread lineage retained.",
      },
      {
        id: "confidence",
        label: "Confidence",
        status: "warning",
        detail: "Validation has not yet completed.",
      },
      {
        id: "education",
        label: "Educational Mapping",
        status: "healthy",
        detail: "Mapped to Decision Intelligence.",
      },
    ],
  },
];
