import { uid } from "@/lib/persistence";
import type { ImportedRepo } from "@/providers/types";

export interface TransformStage { id: string; label: string; status: "queued" | "running" | "done"; at: number }
export interface TransformResult { id: string; stages: TransformStage[]; pages: Array<{ path: string; content: string }>; summary: string }

const STAGES = ["Analyze project", "Build architecture plan", "Generate routes", "Produce diffs", "Apply transformation", "Open in Designer"];
const PAGES = ["Home", "Features", "Pricing", "About", "Contact", "FAQ"];

function pageStub(name: string, projectName: string): string {
  return `export default function ${name}Page() {\n  return (\n    <main className=\"min-h-screen\">\n      <h1 className=\"font-display text-4xl\">${name} — ${projectName}</h1>\n      <p className=\"text-muted-foreground mt-4\">Generated by Transform App → Website.</p>\n    </main>\n  );\n}\n`;
}

export async function runTransform(repo: ImportedRepo, onStage?: (s: TransformStage) => void, signal?: AbortSignal): Promise<TransformResult> {
  const stages: TransformStage[] = [];
  for (const label of STAGES) {
    if (signal?.aborted) throw new Error("canceled");
    const s: TransformStage = { id: uid("ts"), label, status: "running", at: Date.now() };
    stages.push(s); onStage?.(s);
    await new Promise((r) => setTimeout(r, 400 + Math.random() * 300));
    const done: TransformStage = { ...s, status: "done", at: Date.now() };
    stages[stages.length - 1] = done; onStage?.(done);
  }
  const pages = PAGES.map((p) => ({ path: `src/pages/website/${p}.tsx`, content: pageStub(p, repo.name) }));
  return { id: uid("xform"), stages, pages, summary: `Generated ${pages.length} website pages from ${repo.name}.` };
}